### ISSUE TITLE
Directives doesn't work

### ISSUE THREAD

**Issue by venoby** [alex-polosky/angular-payments-ts#1]
- added **AngularPaymentsModule** to imports
- added **payments-card** to input
- have error: 
![image](https://user-images.githubusercontent.com/8698885/40662017-d9122a8a-635d-11e8-9045-86931a9f53e2.png)

what I do bad? 
angular: 5.2

**Comment by alex-polosky** [comment]
@venoby Sorry for the late response, I never got a notification. Did you add AngularPaymentsTS to your module's imports?
